package com.pelizzaris.sufs.domain.model.util;

public enum AcaoAuditoria {
    FALTA_REGISTRADA,
    FALTA_ATUALIZADA,
    FALTA_DELETADA,
    ALUNO_CRIADO,
    ALUNO_ATUALIZADO,
    ALUNO_DESATIVADO,
    ALUNO_ATIVADO,
    USUARIO_CRIADO,
    USUARIO_ATUALIZADO,
    USUARIO_DESATIVADO,
    USUARIO_ATIVADO,
    TURMA_REGISTRADA,
    TURMA_ATUALIZADA,
    TURMA_DELETADA,
}
