spring.application.name=sufs
# server.servlet.context-path=/sufs

spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key