spring.application.name=sufs

spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

logging.file.name=logs/sufs-api.log

jwt.secret=${JWT_SECRET}
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key